/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { IdentityRegistry } from "./IdentityRegistry";
export type { ReputationRegistry } from "./ReputationRegistry";
export * as factories from "./factories";
export { IdentityRegistry__factory } from "./factories/IdentityRegistry__factory";
export type { ISigil } from "./interfaces/ISigil";
export { ISigil__factory } from "./factories/interfaces/ISigil__factory";
export { ReputationRegistry__factory } from "./factories/ReputationRegistry__factory";
