/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ISigil {
  export type AttestationStruct = {
    attestor: AddressLike;
    subject: AddressLike;
    outcome: string;
    onTime: boolean;
    timestamp: BigNumberish;
    signature: BytesLike;
  };

  export type AttestationStructOutput = [
    attestor: string,
    subject: string,
    outcome: string,
    onTime: boolean,
    timestamp: bigint,
    signature: string
  ] & {
    attestor: string;
    subject: string;
    outcome: string;
    onTime: boolean;
    timestamp: bigint;
    signature: string;
  };
}

export interface ReputationRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "attest"
      | "getAttestationCount"
      | "getAttestations"
      | "getScore"
      | "registerAgent"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AttestationRecorded"): EventFragment;

  encodeFunctionData(
    functionFragment: "attest",
    values: [AddressLike, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getAttestationCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAttestations",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "attest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAttestationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAttestations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getScore", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
}

export namespace AttestationRecordedEvent {
  export type InputTuple = [
    attestor: AddressLike,
    subject: AddressLike,
    outcome: string
  ];
  export type OutputTuple = [
    attestor: string,
    subject: string,
    outcome: string
  ];
  export interface OutputObject {
    attestor: string;
    subject: string;
    outcome: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReputationRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ReputationRegistry;
  waitForDeployment(): Promise<this>;

  interface: ReputationRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attest: TypedContractMethod<
    [subject: AddressLike, outcome: string, onTime: boolean],
    [void],
    "nonpayable"
  >;

  getAttestationCount: TypedContractMethod<
    [subject: AddressLike],
    [bigint],
    "view"
  >;

  getAttestations: TypedContractMethod<
    [subject: AddressLike],
    [ISigil.AttestationStructOutput[]],
    "view"
  >;

  getScore: TypedContractMethod<[subject: AddressLike], [bigint], "view">;

  registerAgent: TypedContractMethod<
    [agent: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attest"
  ): TypedContractMethod<
    [subject: AddressLike, outcome: string, onTime: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAttestationCount"
  ): TypedContractMethod<[subject: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAttestations"
  ): TypedContractMethod<
    [subject: AddressLike],
    [ISigil.AttestationStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getScore"
  ): TypedContractMethod<[subject: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<[agent: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AttestationRecorded"
  ): TypedContractEvent<
    AttestationRecordedEvent.InputTuple,
    AttestationRecordedEvent.OutputTuple,
    AttestationRecordedEvent.OutputObject
  >;

  filters: {
    "AttestationRecorded(address,address,string)": TypedContractEvent<
      AttestationRecordedEvent.InputTuple,
      AttestationRecordedEvent.OutputTuple,
      AttestationRecordedEvent.OutputObject
    >;
    AttestationRecorded: TypedContractEvent<
      AttestationRecordedEvent.InputTuple,
      AttestationRecordedEvent.OutputTuple,
      AttestationRecordedEvent.OutputObject
    >;
  };
}
